// Uploaded files on disk. The files table only holds details; the bytes live in server/uploads.
import fs from 'node:fs/promises';
import path from 'node:path';
import config from '../config/index.js';
import * as File from '../database-queries/fileModel.js';
import { MAX_FILES } from '../request-filters/upload.js';
import { HttpError } from './httpError.js';

// Where a file's bytes are. stored_name is always generated by us (see request-filters/upload.js),
// never taken from the person uploading, so it cannot point outside the uploads folder.
export function pathOnDisk(file) {
  return path.join(config.uploadDir, file.stored_name);
}

// Deletes files completely: first the database rows (so nothing can offer a broken download),
// then the bytes. A file already missing from disk is not an error; the goal is that it is gone.
export async function discardFiles(files) {
  for (const file of files) await File.remove(file.id);
  await Promise.all(files.map((file) => fs.rm(pathOnDisk(file), { force: true })));
}

// Deletes files multer has just written to disk for a request that then failed, so a refused
// upload never leaves bytes behind. These have no database rows yet.
export async function discardUploads(uploads = []) {
  await Promise.all(uploads.map((upload) => fs.rm(upload.path, { force: true })));
}

// Refuses an upload that would take something past its total (MAX_FILES in upload.js). Called
// after the upload filter with the files just saved, which are deleted if they are too many.
// For lessons it is also called before, with no files, so a full lesson gets nothing written at
// all (a lesson upload always carries files; a hand-in may carry only a changed answer).
export async function checkFileTotal(ownerType, ownerId, uploads = []) {
  const already = ownerId ? (await File.listFor(ownerType, ownerId)).length : 0;
  const room = MAX_FILES[ownerType] - already;
  if (uploads.length === 0 ? room <= 0 : uploads.length > room) {
    await discardUploads(uploads);
    throw new HttpError(409, room <= 0
      ? `This already holds ${MAX_FILES[ownerType]} files, the most allowed. Remove one first.`
      : `This can hold ${room} more file(s); you sent ${uploads.length}.`);
  }
}

// Records the files the upload filter just saved (req.files) as attached to one thing, e.g.
// ('lesson', 12). If recording fails part way, removes the rows already written and every
// uploaded file, so a failed upload leaves nothing behind on disk or in the table.
export async function recordUploads(uploads, { ownerType, ownerId, uploadedBy }) {
  const ids = [];
  try {
    for (const upload of uploads) {
      ids.push(
        await File.create({
          uploadedBy,
          ownerType,
          ownerId,
          originalName: upload.originalname.slice(0, 255),
          storedName: upload.filename,
          mimeType: upload.mimetype,
          sizeBytes: upload.size,
        }),
      );
    }
  } catch (error) {
    for (const id of ids) await File.remove(id);
    await discardUploads(uploads);
    throw error;
  }
}
