// Uploaded files on disk. The files table only holds details; the bytes live in server/uploads.
import fs from 'node:fs/promises';
import path from 'node:path';
import config from '../config/index.js';
import * as File from '../database-queries/fileModel.js';

// Where a file's bytes are. stored_name is always generated by us (see request-filters/upload.js),
// never taken from the person uploading, so it cannot point outside the uploads folder.
export function pathOnDisk(file) {
  return path.join(config.uploadDir, file.stored_name);
}

// Deletes files completely: first the database rows (so nothing can offer a broken download),
// then the bytes. A file already missing from disk is not an error; the goal is that it is gone.
export async function discardFiles(files) {
  for (const file of files) await File.remove(file.id);
  await Promise.all(files.map((file) => fs.rm(pathOnDisk(file), { force: true })));
}

// Deletes files multer has just written to disk for a request that then failed, so a refused
// upload never leaves bytes behind. These have no database rows yet.
export async function discardUploads(uploads = []) {
  await Promise.all(uploads.map((upload) => fs.rm(upload.path, { force: true })));
}
